---
- name: "Install NGINX for Centos, Debian, Ubuntu"
  hosts: all_servers
  become: yes

#  vars:
#       source_file: 
#       dest_file: 

  tasks:
  - name: "Print OS family"
    ansible.builtin.debug:
      var: ansible_os_family

  - name: Block for Centos
    when: ansible_os_family == "RedHat"
    block:
      - name:
        ansible.builtin.copy:
          src: ./files/nginx/nginx.repo
          dest: /etc/yum.repos.d/nginx.repo
          owner: root
          group: root
          mode: '0644'

      - name: "Make updates for repo and packedges before nginx installation"
        ansible.builtin.shell: "yum update -y"

      - name: "Install NGinx Centos"
        ansible.builtin.dnf: 
          name: nginx 
          state: latest

      - name: "Firewall configuring for Centos NGinx access"
        ansible.builtin.shell: "firewall-cmd --add-service=http --permanent && firewall-cmd --add-service=https --permanent && firewall-cmd --reload"

      - name: "firewall-cmd rules"
        ansible.builtin.shell: "firewall-cmd --list-all"
        register: results

      - name: "show firewall-cmd rules"
        ansible.builtin.debug:
          var: results.stdout_lines

      - name: "Start and enable Nginx in Centos"
        ansible.builtin.service: 
          name: nginx 
          state: started 
          enabled: true

  - name: "Firewall base installation and configuring for Debian and Ubuntu"
    when: (os == "debian11") or (os == "ubuntu22")
    block:
      - name: "Install ufw for Debian OS"
        ansible.builtin.apt:
          name: ufw
          state: latest

      - name: "configuring ufw for Debian OS"
        ansible.builtin.shell: "ufw default deny incoming ; ufw default allow outgoing ; ufw allow ssh ; sudo ufw allow 22 ; ufw allow http ; ufw allow 80 ; ufw allow https ; ufw allow 443 ; ufw --force enable"

  - name: "Block for Debian and Ubuntu"
    when: ansible_os_family == "Debian"
    block:
      - name: "Update OS and Packedges"
        ansible.builtin.shell: "apt update -y && sudo apt upgrade -y"

      - name: "Install NGinx Debian, Ubuntu"
        ansible.builtin.apt: 
          name: nginx 
          state: latest

      - name: "Firewall configuring for NGinx"
        ansible.builtin.shell: "ufw allow 'nginx full'"

      - name: "show status ufw in Debian and Ubuntu OS"
        ansible.builtin.shell: "ufw status verbose"
        register: results

      - name: "show ufw rules"
        ansible.builtin.debug:
          var: results.stdout_lines

      - name: "Start and enable Nginx"
        ansible.builtin.service: 
          name: nginx 
          state: started 
          enabled: true